# -*- coding: utf-8 -*-

# Form implementation generated from reading ui file 'C:\PycharmProjects\xx\Ui_form.ui'
#
# Created by: PyQt5 UI code generator 5.14.2
#
# WARNING! All changes made in this file will be lost!


from PyQt5 import QtCore, QtGui, QtWidgets
from mplCanvasWrapper import MplCanvasWrapper

class Ui_Form(object):
    def setupUi(self, Form):
        Form.setObjectName("Form")
        Form.resize(826, 684)
        self.groupBox_2 = QtWidgets.QGroupBox(Form)
        self.groupBox_2.setGeometry(QtCore.QRect(20, 20, 291, 281))
        self.groupBox_2.setObjectName("groupBox_2")
        self.open_button = QtWidgets.QPushButton(self.groupBox_2)
        self.open_button.setGeometry(QtCore.QRect(20, 230, 111, 28))
        self.open_button.setObjectName("open_button")
        self.close_button = QtWidgets.QPushButton(self.groupBox_2)
        self.close_button.setGeometry(QtCore.QRect(140, 230, 101, 28))
        self.close_button.setObjectName("close_button")
        self.label = QtWidgets.QLabel(self.groupBox_2)
        self.label.setGeometry(QtCore.QRect(50, 50, 61, 20))
        self.label.setObjectName("label")
        self.comboBox_2 = QtWidgets.QComboBox(self.groupBox_2)
        self.comboBox_2.setGeometry(QtCore.QRect(120, 80, 87, 22))
        self.comboBox_2.setObjectName("comboBox_2")
        self.comboBox_2.addItem("")
        self.comboBox_2.addItem("")
        self.comboBox_2.addItem("")
        self.comboBox_2.addItem("")
        self.comboBox_2.addItem("")
        self.comboBox_5 = QtWidgets.QComboBox(self.groupBox_2)
        self.comboBox_5.setGeometry(QtCore.QRect(120, 170, 87, 22))
        self.comboBox_5.setObjectName("comboBox_5")
        self.comboBox_5.addItem("")
        self.label_3 = QtWidgets.QLabel(self.groupBox_2)
        self.label_3.setGeometry(QtCore.QRect(60, 110, 51, 16))
        self.label_3.setObjectName("label_3")
        self.comboBox = QtWidgets.QComboBox(self.groupBox_2)
        self.comboBox.setGeometry(QtCore.QRect(120, 50, 87, 22))
        self.comboBox.setMouseTracking(False)
        self.comboBox.setTabletTracking(False)
        self.comboBox.setObjectName("comboBox")
        self.comboBox.addItem("")
        self.comboBox.addItem("")
        self.comboBox.addItem("")
        self.comboBox.addItem("")
        self.label_5 = QtWidgets.QLabel(self.groupBox_2)
        self.label_5.setGeometry(QtCore.QRect(60, 170, 51, 16))
        self.label_5.setObjectName("label_5")
        self.label_4 = QtWidgets.QLabel(self.groupBox_2)
        self.label_4.setGeometry(QtCore.QRect(60, 140, 51, 20))
        self.label_4.setObjectName("label_4")
        self.comboBox_3 = QtWidgets.QComboBox(self.groupBox_2)
        self.comboBox_3.setGeometry(QtCore.QRect(120, 110, 87, 22))
        self.comboBox_3.setObjectName("comboBox_3")
        self.comboBox_3.addItem("")
        self.comboBox_3.addItem("")
        self.comboBox_3.addItem("")
        self.comboBox_4 = QtWidgets.QComboBox(self.groupBox_2)
        self.comboBox_4.setGeometry(QtCore.QRect(120, 140, 87, 22))
        self.comboBox_4.setEditable(False)
        self.comboBox_4.setObjectName("comboBox_4")
        self.comboBox_4.addItem("")
        self.label_2 = QtWidgets.QLabel(self.groupBox_2)
        self.label_2.setGeometry(QtCore.QRect(60, 80, 51, 16))
        self.label_2.setObjectName("label_2")
        self.groupBox_5 = QtWidgets.QGroupBox(Form)
        self.groupBox_5.setGeometry(QtCore.QRect(320, 190, 501, 471))
        self.groupBox_5.setObjectName("groupBox_5")
        self.begin_v = QtWidgets.QPushButton(self.groupBox_5)
        self.begin_v.setGeometry(QtCore.QRect(40, 430, 93, 28))
        self.begin_v.setObjectName("begin_v")
        self.stop_v = QtWidgets.QPushButton(self.groupBox_5)
        self.stop_v.setGeometry(QtCore.QRect(370, 430, 93, 28))
        self.stop_v.setObjectName("stop_v")
        self.mplCanvas = MplCanvasWrapper(self.groupBox_5)
        self.mplCanvas.setGeometry(QtCore.QRect(9, 19, 481, 401))
        sizePolicy = QtWidgets.QSizePolicy(QtWidgets.QSizePolicy.Expanding, QtWidgets.QSizePolicy.Expanding)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.mplCanvas.sizePolicy().hasHeightForWidth())
        self.mplCanvas.setSizePolicy(sizePolicy)
        self.mplCanvas.setAutoFillBackground(False)
        self.mplCanvas.setObjectName("mplCanvas")
        self.groupBox_3 = QtWidgets.QGroupBox(Form)
        self.groupBox_3.setGeometry(QtCore.QRect(20, 330, 291, 151))
        self.groupBox_3.setObjectName("groupBox_3")
        self.send_c = QtWidgets.QCheckBox(self.groupBox_3)
        self.send_c.setGeometry(QtCore.QRect(210, 70, 91, 19))
        self.send_c.setObjectName("send_c")
        self.send_edi = QtWidgets.QTextEdit(self.groupBox_3)
        self.send_edi.setGeometry(QtCore.QRect(10, 60, 191, 31))
        self.send_edi.setObjectName("send_edi")
        self.send_button = QtWidgets.QPushButton(self.groupBox_3)
        self.send_button.setGeometry(QtCore.QRect(10, 100, 101, 28))
        self.send_button.setObjectName("send_button")
        self.clear_s_button = QtWidgets.QPushButton(self.groupBox_3)
        self.clear_s_button.setGeometry(QtCore.QRect(130, 100, 71, 28))
        self.clear_s_button.setObjectName("clear_s_button")
        self.send_t_c = QtWidgets.QCheckBox(self.groupBox_3)
        self.send_t_c.setGeometry(QtCore.QRect(10, 30, 91, 19))
        self.send_t_c.setObjectName("send_t_c")
        self.label_6 = QtWidgets.QLabel(self.groupBox_3)
        self.label_6.setGeometry(QtCore.QRect(160, 30, 41, 16))
        self.label_6.setObjectName("label_6")
        self.t_edi = QtWidgets.QLineEdit(self.groupBox_3)
        self.t_edi.setGeometry(QtCore.QRect(100, 30, 51, 21))
        self.t_edi.setObjectName("t_edi")
        self.groupBox_4 = QtWidgets.QGroupBox(Form)
        self.groupBox_4.setGeometry(QtCore.QRect(320, 20, 501, 151))
        self.groupBox_4.setObjectName("groupBox_4")
        self.rec_txt = QtWidgets.QTextBrowser(self.groupBox_4)
        self.rec_txt.setGeometry(QtCore.QRect(20, 30, 371, 111))
        self.rec_txt.setObjectName("rec_txt")
        self.clear_res_button = QtWidgets.QPushButton(self.groupBox_4)
        self.clear_res_button.setGeometry(QtCore.QRect(400, 110, 93, 28))
        self.clear_res_button.setObjectName("clear_res_button")
        self.res_c = QtWidgets.QCheckBox(self.groupBox_4)
        self.res_c.setGeometry(QtCore.QRect(400, 60, 91, 19))
        self.res_c.setObjectName("res_c")
        self.groupBox = QtWidgets.QGroupBox(Form)
        self.groupBox.setGeometry(QtCore.QRect(20, 500, 291, 161))
        self.groupBox.setObjectName("groupBox")
        self.lineEdit = QtWidgets.QLineEdit(self.groupBox)
        self.lineEdit.setGeometry(QtCore.QRect(70, 100, 113, 21))
        self.lineEdit.setObjectName("lineEdit")
        self.label_7 = QtWidgets.QLabel(self.groupBox)
        self.label_7.setGeometry(QtCore.QRect(10, 100, 72, 15))
        self.label_7.setObjectName("label_7")
        self.label_8 = QtWidgets.QLabel(self.groupBox)
        self.label_8.setGeometry(QtCore.QRect(10, 50, 72, 15))
        self.label_8.setObjectName("label_8")
        self.lineEdit_2 = QtWidgets.QLineEdit(self.groupBox)
        self.lineEdit_2.setGeometry(QtCore.QRect(70, 50, 113, 21))
        self.lineEdit_2.setObjectName("lineEdit_2")
        self.groupBox_3.raise_()
        self.groupBox_5.raise_()
        self.groupBox_4.raise_()
        self.groupBox_2.raise_()
        self.groupBox.raise_()

        self.retranslateUi(Form)
        QtCore.QMetaObject.connectSlotsByName(Form)

    def retranslateUi(self, Form):
        _translate = QtCore.QCoreApplication.translate
        Form.setWindowTitle(_translate("Form", "Form"))
        self.groupBox_2.setTitle(_translate("Form", "串口设置"))
        self.open_button.setText(_translate("Form", "打开串口"))
        self.close_button.setText(_translate("Form", "关闭串口"))
        self.label.setText(_translate("Form", "串口选择"))
        self.comboBox_2.setItemText(0, _translate("Form", "2400"))
        self.comboBox_2.setItemText(1, _translate("Form", "4800"))
        self.comboBox_2.setItemText(2, _translate("Form", "9600"))
        self.comboBox_2.setItemText(3, _translate("Form", "14400"))
        self.comboBox_2.setItemText(4, _translate("Form", "19200"))
        self.comboBox_5.setItemText(0, _translate("Form", "1"))
        self.label_3.setText(_translate("Form", "数据位"))
        self.comboBox.setItemText(0, _translate("Form", "COM1"))
        self.comboBox.setItemText(1, _translate("Form", "COM2"))
        self.comboBox.setItemText(2, _translate("Form", "COM3"))
        self.comboBox.setItemText(3, _translate("Form", "COM4"))
        self.label_5.setText(_translate("Form", "停止位"))
        self.label_4.setText(_translate("Form", "校验位"))
        self.comboBox_3.setItemText(0, _translate("Form", "8"))
        self.comboBox_3.setItemText(1, _translate("Form", "16"))
        self.comboBox_3.setItemText(2, _translate("Form", "4"))
        self.comboBox_4.setItemText(0, _translate("Form", "N"))
        self.label_2.setText(_translate("Form", "波特率"))
        self.groupBox_5.setTitle(_translate("Form", "图像数据"))
        self.begin_v.setText(_translate("Form", "开始显示"))
        self.stop_v.setText(_translate("Form", "停止显示"))
        self.groupBox_3.setTitle(_translate("Form", "发送区"))
        self.send_c.setText(_translate("Form", "hex发送"))
#         self.send_edi.setHtml(_translate("Form", "<!DOCTYPE HTML PUBLIC \"-//W3C//DTD HTML 4.0//EN\" \"http://www.w3.org/TR/REC-html40/strict.dtd\">\n"
# "<html><head><meta name=\"qrichtext\" content=\"1\" /><style type=\"text/css\">\n"
# "p, li { white-space: pre-wrap; }\n"
# "</style></head><body style=\" font-family:\'SimSun\'; font-size:9pt; font-weight:400; font-style:normal;\">\n"
# "<p style=\" margin-top:0px; margin-bottom:0px; margin-left:0px; margin-right:0px; -qt-block-indent:0; text-indent:0px;\">123456</p>\n"
# "<p style=\"-qt-paragraph-type:empty; margin-top:0px; margin-bottom:0px; margin-left:0px; margin-right:0px; -qt-block-indent:0; text-indent:0px;\"><br /></p></body></html>"))
        self.send_button.setText(_translate("Form", "发送"))
        self.clear_s_button.setText(_translate("Form", "清除"))
        self.send_t_c.setText(_translate("Form", "定时发送"))
        self.label_6.setText(_translate("Form", "ms/s"))
        self.t_edi.setText(_translate("Form", "1000"))
        self.groupBox_4.setTitle(_translate("Form", "接受数据"))
        self.clear_res_button.setText(_translate("Form", "清空"))
        self.res_c.setText(_translate("Form", "hex接受"))
        self.groupBox.setTitle(_translate("Form", "串口状态"))
        self.label_7.setText(_translate("Form", "已发送："))
        self.label_8.setText(_translate("Form", "已接受："))

